# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [5]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [6]:
# your code here
print(np.__version__)

1.17.3


#### 3. Generate a 3x2x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [11]:
# Method 1
a = np.random.rand(3, 2, 5)

In [13]:
# Method 2
a = np.random.randn(3, 2, 5)

In [14]:
# Method 3
a = np.random.randint(10, size=(3, 2, 5))

#### 4. Print *a*.


In [15]:
# your code here
print(a)

[[[5 8 0 6 1]
  [4 0 7 2 4]]

 [[4 3 9 7 2]
  [9 3 9 5 6]]

 [[4 8 9 7 4]
  [7 5 5 4 0]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [16]:
# your code here
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [17]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [19]:
# your code here
a.shape == b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [21]:
# your answer here
# no, they have different shapes

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [46]:
# your code here
c = b.T

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [24]:
# your code/answer here
d = a + c
# arrays a and c have the same shape

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [33]:
# your code/answer here
print(a)
print(d)
# the vaues in array a are integers; the values in array b are floats

[[[5 8 0 6 1]
  [4 0 7 2 4]]

 [[4 3 9 7 2]
  [9 3 9 5 6]]

 [[4 8 9 7 4]
  [7 5 5 4 0]]]
[[[ 6.  9.  1.  7.  2.]
  [ 5.  1.  8.  3.  5.]]

 [[ 5.  4. 10.  8.  3.]
  [10.  4. 10.  6.  7.]]

 [[ 5.  9. 10.  8.  5.]
  [ 8.  6.  6.  5.  1.]]]


True

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [26]:
# your code here
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [29]:
# your code/answer here
e == a
# they are equal because python implicitly converts int to float before comparing

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [34]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [58]:
# your code here
f = np.empty(d.shape)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [83]:
# your code here
d_flat = d.flatten()
f_flat = f.flatten()
for idx, val in enumerate(d_flat):
    if val > d_min and val < d_mean:
        f_flat[idx] = 25
    elif val > d_mean and val < d_max:
        f_flat[idx] = 75
    elif val == d_mean:
        f_flat[idx] = 50
    elif val == d_min:
        f_flat[idx] = 0
    elif val == d_max:
        f_flat[idx] = 100

f = np.reshape(f_flat, f.shape)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
  [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981]],
 
 [[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042],
  [1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381]],
 
 [[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
  [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
  [ 75.,  75.,  25.,  25.,  25.]],
 
 [[ 75.,  25.,  75.,  75.,  75.],
  [ 25.,  25.,  25.,  25., 100.]],

 [[ 75.,  75.,  75.,  75.,  75.],
  [ 25.,  75.,   0.,  75.,  75.]]]
```

In [84]:
# your code here
print(d)
print(f)

[[[ 6.  9.  1.  7.  2.]
  [ 5.  1.  8.  3.  5.]]

 [[ 5.  4. 10.  8.  3.]
  [10.  4. 10.  6.  7.]]

 [[ 5.  9. 10.  8.  5.]
  [ 8.  6.  6.  5.  1.]]]
[[[ 75.  75.   0.  75.  25.]
  [ 25.   0.  75.  25.  25.]]

 [[ 25.  25. 100.  75.  25.]
  [100.  25. 100.  75.  75.]]

 [[ 25.  75. 100.  75.  25.]
  [ 75.  75.  75.  25.   0.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
  [ 'D',  'D',  'B',  'B',  'B']],
 
 [[ 'D',  'B',  'D',  'D',  'D'],
  [ 'B',  'B',  'B',  'B',  'E']],

 [[ 'D',  'D',  'D',  'D',  'D'],
  [ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [116]:
# your code here
g = np.empty(f.shape, dtype='object')
g_flat = g.flatten()

for idx, val in enumerate(f_flat):
    if val == 0:
        g_flat[idx] = 'A'
    elif val == 25:
        g_flat[idx] = 'B'
    elif val == 50:
        g_flat[idx] = 'C'
    elif val == 75:
        g_flat[idx] = 'D'
    elif val == 100:
        g_flat[idx] = 'E'
        
np.reshape(g_flat, g.shape)

array([[['D', 'D', 'A', 'D', 'B'],
        ['B', 'A', 'D', 'B', 'B']],

       [['B', 'B', 'E', 'D', 'B'],
        ['E', 'B', 'E', 'D', 'D']],

       [['B', 'D', 'E', 'D', 'B'],
        ['D', 'D', 'D', 'B', 'A']]], dtype=object)